<a href="https://colab.research.google.com/github/SanwithaReddy/Gen-AI-2025/blob/main/2403a52l09_01_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [2]:
Yactual = [20,30,40,50,60]
Ypredicted = [20.5,30.3,40.2,50.6,60.7]

measured = np.array(Yactual)
predicted = np.array(Ypredicted)

print("Measured data:", measured)
print("Predicted data:", predicted)

Measured data: [20 30 40 50 60]
Predicted data: [20.5 30.3 40.2 50.6 60.7]


In [3]:
mse = mean_squared_error(measured, predicted)


In [4]:
rmse = np.sqrt(mse)

In [5]:
mape = np.mean(np.abs((measured - predicted) / measured)) * 100

In [6]:
r2 = r2_score(measured, predicted)

In [7]:
print(f"Mean Square Error (MSE): {mse}")
print(f"Root Mean Square Error (RMSE): {rmse}")
print(f"Mean Absolute Percentage Error (MAPE): {mape}%")
print(f"R-squared (R²): {r2}")

Mean Square Error (MSE): 0.24600000000000147
Root Mean Square Error (RMSE): 0.49598387070549127
Mean Absolute Percentage Error (MAPE): 1.273333333333337%
R-squared (R²): 0.99877


# Regression Metrics

In [8]:
ya=[20,30,40,50,60]
yp=[20.5,30.3,40.2,50.6,60.7]

# WithOut Libraries

In [9]:
total = 0
for i in range(len(ya)):
  total = total + (ya[i] - yp[i])**2
mse = total / len(ya)
print("mean square error : ", mse)

mean square error :  0.24600000000000147


In [10]:
print("Root mean square error : ",(mse)**0.5)

Root mean square error :  0.49598387070549127


# With Libraries

In [11]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,root_mean_squared_error

In [12]:
print("mean square error : ",mean_squared_error(ya,yp))
print("mean absolute error : ",mean_absolute_error(ya,yp))
print("Root mean square error : ",root_mean_squared_error(ya,yp))

mean square error :  0.24600000000000147
mean absolute error :  0.4600000000000016
Root mean square error :  0.49598387070549127


# Classification Metrics

In [13]:

ya1=[0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2]
yp1=[0,0,1,2,2,1,0,2,0,2,2,0,0,1,2,2]

# WithOut Libraries

In [14]:
min_label = min(min(ya1), min(yp1))
max_label = max(max(ya1), max(yp1))
num_classes = max_label - min_label + 1

cm = [[0 for _ in range(num_classes)] for _ in range(num_classes)]

for i in range(len(ya1)):
    cm[ya1[i]-min_label][yp1[i]-min_label] += 1

for row in cm:
    print(row)

[2, 1, 2]
[2, 1, 3]
[2, 1, 2]


In [15]:
import numpy as np

In [16]:
accuracy = np.sum(np.diagonal(cm)) / np.sum(cm)

precision = {}
recall = {}
f1_score = {}

for i in range(num_classes):
    true_positive = cm[i][i]
    false_positive = np.sum(cm[j][i] for j in range(num_classes)) - true_positive
    false_negative = np.sum(cm[i][j] for j in range(num_classes)) - true_positive
    true_negative = np.sum(np.sum(cm[row][col] for col in range(num_classes)) for row in range(num_classes)) - (true_positive + false_positive + false_negative)

    # Precision: TP / (TP + FP)
    precision[i] = true_positive / (true_positive + false_positive) if (true_positive + false_positive) > 0 else 0

    # Recall: TP / (TP + FN)
    recall[i] = true_positive / (true_positive + false_negative) if (true_positive + false_negative) > 0 else 0

    # F1 Score: 2 * (Precision * Recall) / (Precision + Recall)
    if precision[i] + recall[i] > 0:
        f1_score[i] = 2 * (precision[i] * recall[i]) / (precision[i] + recall[i])
    else:
        f1_score[i] = 0
# Calculate overall precision, recall, and F1-score using numpy
overall_precision = np.sum([precision[i] for i in range(num_classes)])/num_classes
overall_recall = np.sum([recall[i] for i in range(num_classes)])/num_classes
overall_f1_score = np.sum([f1_score[i] for i in range(num_classes)])/num_classes

# Print results
for i in range(num_classes):
    print(f"\nClass {i + min_label}:")
    print(f"  Precision: {precision[i]:.2f}")
    print(f"  Recall: {recall[i]:.2f}")
    print(f"  F1-Score: {f1_score[i]:.2f}")


print("\nMetrics:")
print(f"Overall Accuracy: {accuracy:.2f}")
print(f"Overall Precision: {overall_precision:.2f}")
print(f"Overall Recall: {overall_recall:.2f}")
print(f"Overall F1-Score: {overall_f1_score:.2f}")

print()
print()


Class 0:
  Precision: 0.33
  Recall: 0.40
  F1-Score: 0.36

Class 1:
  Precision: 0.33
  Recall: 0.17
  F1-Score: 0.22

Class 2:
  Precision: 0.29
  Recall: 0.40
  F1-Score: 0.33

Metrics:
Overall Accuracy: 0.31
Overall Precision: 0.32
Overall Recall: 0.32
Overall F1-Score: 0.31




<ipython-input-16-5d922b0979af>:9: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  false_positive = np.sum(cm[j][i] for j in range(num_classes)) - true_positive
<ipython-input-16-5d922b0979af>:10: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  false_negative = np.sum(cm[i][j] for j in range(num_classes)) - true_positive
<ipython-input-16-5d922b0979af>:11: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  true_negative = np.sum(np.sum(cm[row][col] for col in range(num_classes)) for row in range(num_classes)) - (true_positive + false_positive + false_negative)


# With Libraries

In [17]:
from sklearn.metrics import accuracy_score,precision_score,f1_score,recall_score,classification_report,confusion_matrix

In [18]:
print(confusion_matrix(ya1,yp1))

[[2 1 2]
 [2 1 3]
 [2 1 2]]


In [19]:
print(classification_report(ya1,yp1))

              precision    recall  f1-score   support

           0       0.33      0.40      0.36         5
           1       0.33      0.17      0.22         6
           2       0.29      0.40      0.33         5

    accuracy                           0.31        16
   macro avg       0.32      0.32      0.31        16
weighted avg       0.32      0.31      0.30        16



In [20]:
print("\nMetrics:")
print(f"Overall Accuracy: {accuracy_score(ya1,yp1):.2f}")
print(f"Overall Precision: {precision_score(ya1,yp1, average='weighted'):.2f}")
print(f"Overall Recall: {recall_score(ya1,yp1, average='weighted'):.2f}")
print(f"Overall F1-Score: {f1_score(ya1,yp1, average='weighted'):.2f}")


Metrics:
Overall Accuracy: 0.31
Overall Precision: 0.32
Overall Recall: 0.31
Overall F1-Score: 0.30
